### ISSUE TITLE
Please add imagebreed to database list

### ISSUE THREAD

**Issue by nickmorales** [mverouden/brapir#1]
https://imagebreed.org 

Thank you

**Comment by mverouden** [comment]
Hello Nick,

Thank you for your request. You have made this request for the v1 repo. Do you also want this address to be added to v2 (https://github.com/mverouden/brapir-v2)?

The as.brapi_db() function has the following default arguments: secure = FALSE,  protocol = "http://",  db = "127.0.0.1", port = 80,  apipath = NULL,  multicrop = FALSE,  commoncropname = "",  user = "",  password = "",  token = "", granttype = "password", clientid = "brapir", bms = FALSE

I have added  imagebreed into the whitelist brapi_db() function using the following values:
```
imagebreed <-  as.brapi_db(secure = TRUE,
                           protocol = "https://",
                           db = "imagebreed.org",
                           port = 443,
                           multicrop = TRUE,
                           bms = FALSE)
```
Since you only provided the url I have to asume that ImageBreed uses the default apipath for the BrAPI calls (e.g. brapi/v1). Furthermore I assume that it is using port 443 for the https protocol and that it is a multicrop system.

Before pushing it to the repo, could you confirm that this is correct? Otherwise please provide the correct settings.

Regards,
Maikel

**Comment by nickmorales** [comment]
Thank you Maikel,
I assume multicrop means there are many species in the database? That is
true in imagebreed there is maize, alfalfa, barley, etc. but there is
no change in the brapi url for each crop. They are all accessible at
https://imagebreed.org with no URL modification, so I assume that means
multicrop = FALSE. I could be wrong in interpreting this though.
By providing a user and password will it automatically login? I created a
test account for this purpose.

So I think this is more accurate:

imagebreed <-  as.brapi_db(secure = TRUE,
                           protocol = "https://",
                           db = "imagebreed.org",
                           port = 80,

user = "BrapiRv1",
password = "BrapiRv12022testpass",
granttype = "password"
commoncropname = c( "maize", "alfalfa"),
apipath = NULL,
multicrop = FALSE,
bms = FALSE

)

**Comment by mverouden** [comment]
Hi Nick,

I still find it tremendously confusing, that the BTI bases (such as cassavabase.org, sweetpotatobase.org and now imagebreed.org) use https as protocol over port 80. Although this is technically allowed, the combination used is more than a little unorthodox. Anyway, I have adapted your provided values into the brapi_db() function of listed databases.

The function argument `commoncropname` should be only 1 crop and is used in the `multicrop = TRUE` situation to create the appropriate URL for a call. Therefore, there is no need to specify this in your situation.

Function arguments `user` and `password` are used in the brapi_login() function using the /token call from the BrAPI v1 specs to obtain the `token` in the connection object . Although this call has been deprecated for a long time, it is still in use within the Breeding Management System (BMS) for lack of an authentication server to hand a token to the connection object within R. Therefore, these function arguments (`user`, and `password`) are also kept for backward compatibility reasons. The most important part in the connection object is the `token` field, which needs to be filled to make calls on a database with authentication.

**Login within R is not automatic**, because on a database with authentication the `token` needs to be retrieved first. I have tried your test account and the following works perfectly in R with the BrAPIR v1 package:

```
### Load the BrAPIR v1 package
library(brapirv1)

### Create a BrAPI connection object
con <- brapi_db()$imagebreed

### Fill username and password in the connection object
con$user <- "BrapiRv1"
con$password <- "BrapiRv12022testpass"

### Retrieve the token for making the calls
con <- brapi_login(con = con)

### Example calls
brapi_get_calls(con = con)
brapi_get_studies(con = con)
```
Regards,
Maikel

**Comment by nickmorales** [comment]
Hi Maikel,
Thank you for the info. I was following the examples in the code for
defining it, if you think using port 443 is more clear with the https then
please change it.

Maybe it could be a nice behavior if it would automatically login at the
same time that 'con <- brapi_db()$imagebreed' is called using the provided
user and password as defaults?

Thank you,
Nick

**Comment by mverouden** [comment]
Hi Nick,

It is not up to me to change the combination of protocol and port used, because it depends on the implementation of ImageBreed.org. Normally SSL/TLS is operates through port 443 and is in that sense linked to the https:// protocol. However, it all depends on how it has been configured on the server-side.

The goal of the BrAPIR package is to implement all BrAPI specifications for use from with R. With the supplied functions you can write your own automatic login to a dedicated server. The brapi_db() function  was and is offered as a kindness to have compatible databases already configured with respect to the required settings.

Offering automatic login would indeed be nice, but way too much work to implement with all the different implementations based on the BrAPI specs for the various databases. Login was part of v1.0 and has been deprecated since v1.1. Authentication has never been part of the BrAPI specs, this is fully up to the database implementation.  I am planning to look into Authentication to retrieve a token via OAUTH2  on an authentication server without supplying user and password in the R functions for safety reasons, but first I need to finish the v2 implementation.

Being the only developer on BrAPIR this is already one hell of a job to do in my spare time. Soon v2.1 of the BrAPI specifications will be released, which will probably mean a huge overhaul again while keeping backward compatibility.

Warm regards,
Maikel

**Comment by nickmorales** [comment]
Thank you for the help.

Using port 443 would be better. There is a forwarding between 80 to 443 that lets it work either way.

That clarifies the login situation, but maybe the brapi_db() could try the brapi_login() using the defined user and password? It could simplify the situation for retrieving the access_token. Just a suggestion.

Certainly there is a lot of work to maintain this, so thank you for your contributions!

**Comment by mverouden** [comment]
Hi Nick,

I have changed the port to 443 (in `brapi_db()`) for you and created [`brapi_imagebreed_login()`](https://github.com/mverouden/brapir-v1/blob/master/R/brapi_imagebreed_login.R) and [`brapi_imagebreed_logout()`](https://github.com/mverouden/brapir-v1/blob/master/R/brapi_imagebreed_logout.R) functions with documentation.

Unfortunately you removed the test login already, therefore, I wasn't able to test them.

Please let me know if they work,

Regards,
Maikel
